### ISSUE TITLE
Great tool!

### ISSUE THREAD

**Issue by zachtdavis** [clarity99/bittrex-tradeanalyzer#1]
Sorry for creating an issue, it runs great, no issues. I was using the DLL you included with this project and I noticed it doesnt have the "getmarketsummaries" (not to be confused with "getmarketsummary" which it does have).

Is this your DLL or is it someone elses project? Basically Im looking to get the getmarketsummaries incorporated into the DLL or find the source add it myself and use that.

Thank you in advance!

**Comment by clarity99** [comment]
Bittrex dll is from my fork of https://github.com/Griffitsj/csharp-bittrex-api.git with added async - I didn't have time yet to submit a pull request.
For getmarketsummaries I use
```
public class MarketSummary
  {
    public string MarketName { get; set; }
    public decimal? High { get; set; }
    public decimal? Low { get; set; }
    public decimal? Volume { get; set; }
    public decimal? Last { get; set; }
    public decimal? Bid { get; set; }
    public decimal? Ask { get; set; }
    public decimal? OpenBuyOrders { get; set; }
    public decimal? OpenSellOrders { get; set; }
    public DateTime TimeStamp { get; set; }
  }

public static async Task<IEnumerable<MarketSummary>> GetMarketSummaries()
 {
     var url = "https://bittrex.com/api/v1.1/public/getmarketsummaries";
     var r = await new HttpClient().GetStringAsync(url).ConfigureAwait(false);
     
      var ms = JObject.Parse(r);
      JToken msP = ms["result"];
     
      var msSumamries = JsonConvert.DeserializeObject<MarketSummary[]>(msP.ToString());
     
      return msSumamries;
```

**Comment by zachtdavis** [comment]
Thank you much! :)
